[project]
name = "leadheatapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "authlib>=1.6.0",
    "beautifulsoup4>=4.14.3",
    "crawl4ai>=0.8.6",
    "dateparser>=1.4.0",
    "fastapi[standard-no-fastapi-cloud-cli]>=0.135.2",
    "itsdangerous>=2.2.0", # required by `starlette.middleware.sessions`
    "linkedin-scraper>=3.1.2",
    "pdfplumber>=0.11.8",
    "requests>=2.33.1",
    "requests-futures>=1.0.2",
    "six>=1.17.0",
    "sqlalchemy>=2.0.49",
    "xmltodict>=1.0.4",
]
